# language: objective-c
# xcode_workspace: Example/Example.xcworkspace
# xcode_scheme: Example

# language: objective-c
# before_install:
#     - brew update
#     - brew install xctool
# script: travis/script.sh
